@startuml
!theme future-white from https://raw.githubusercontent.com/hokorobi/plantuml-theme-future/master

entity Client
participant Backend
participant Queue
database RDB
entity External

@enduml

